### ISSUE TITLE
API nie działa.

### ISSUE THREAD

**Issue by Axyvii** [CyberWord-YouTube/Projectman#2]
Pomimo uruchomienia aplikacji wymaganych do prawidłowego funkcjonowania aplikacji, nie odpala się.
![image 1](https://user-images.githubusercontent.com/118563924/227025602-c3328a8c-6b46-4a58-bd9e-f6f4573c8948.png)
Czy zrobiłam coś nie tak?

**Comment by CyberWord-YouTube** [comment]
To znaczy:
1. WinApplication nie jest funkcjonalny
2. Sam serwer (z przyczyn osa) musi być uruchomiony jako administrator.
3. WWW i config zrobie aby ładowało się z katalogu kodu

**Comment by Axyvii** [comment]
dobra, dzieki
